/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class distance */

#ifndef _Included_distance
#define _Included_distance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     distance
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_distance_setup
  (JNIEnv *, jclass);

/*
 * Class:     distance
 * Method:    getDistance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_distance_getDistance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
