/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sonar */

#ifndef _Included_Sonar
#define _Included_Sonar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sonar
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Sonar_setup
  (JNIEnv *, jclass);

/*
 * Class:     Sonar
 * Method:    getDistance
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Sonar_getDistance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
